### ISSUE TITLE
DKMS install fail after archlinux update to the latest(5.8.14-arch1-1)

### ISSUE THREAD

**Issue by YouYouExcellent** [Mange/rtl8192eu-linux-driver#199] opened 2020-10-09 15:30 UTC
hi,

Today I update my archlinux to the latest (5.8.14-arch1-1)

I find dkms install will fail.

I find there existing redefinition struct.

could you please help me to fix this issue?

thanks!

the make logs are following:

_DKMS make.log for rtl8192eu-1.0 for kernel 5.8.14-arch1-1 (x86_64)
Fri Oct  9 11:18:04 PM UTC 2020
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.8.14-arch1-1/build M=/var/lib/dkms/rtl8192eu/1.0/build  modules
make[1]: Entering directory '/usr/lib/modules/5.8.14-arch1-1/build'
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_io.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_ioctl_query.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_ioctl_set.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_ieee80211.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme_ext.o
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme_ext.c: In function ‘mgt_dispatcher’:
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme_ext.c:1364:6: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1364 |    if(check_fwstate(pmlmepriv, WIFI_AP_STATE) == _TRUE)
      |      ^
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme_ext.c:1369:3: note: here
 1369 |   case WIFI_ASSOCREQ:
      |   ^~~~
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_wlan_util.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_vht.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_pwrctrl.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_rf.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_recv.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_sta_mgt.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_ap.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_xmit.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_p2p.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_tdls.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_br_ext.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:82,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_br_ext.c:32:
/var/lib/dkms/rtl8192eu/1.0/build/include/rtw_security.h:241:8: error: redefinition of ‘struct sha256_state’
  241 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/net/inet_sock.h:22,
                 from ./include/net/ip.h:27,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_br_ext.c:24:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:281: /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_br_ext.o] Error 1
make[1]: *** [Makefile:1752: /var/lib/dkms/rtl8192eu/1.0/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.8.14-arch1-1/build'
make: *** [Makefile:1711: modules] Error 2_

**Comment by CGarces** [comment] 2020-10-09 21:39
duplicate of #197
**sha256_state** no longer exists, was changed to **sha256_state_rtk** on #182
Please ensure that you fetch the last version of **realtek-4.4.x branch**.

**Closed as completed by CGarces** 2020-10-09 21:39 UTC
Labels: duplicate
