### ISSUE TITLE
Slow download on Ubuntu 18.04 - Kernel 4.15.0-32-generic

### ISSUE THREAD

**Issue by February30th** [Mange/rtl8192eu-linux-driver#97] opened 2018-08-17 10:03 UTC
Extreme slow download speed with newer kernel versions, using the realtek-4.4.x branch

![speedtest-screenshot](https://user-images.githubusercontent.com/17834418/44260633-f182f980-a20c-11e8-8f42-7e0279ca72cb.png)

As you can see upload was unaffected but the download speed is abysmal

**Comment by CGarces** [comment] 2018-08-30 06:41
Duplicate of #90

**Closed as completed by CGarces** 2018-08-30 06:41 UTC
Labels: duplicate
