### ISSUE TITLE
Compilation Failure on chromeOS Flex Linux（debian 11 bullseye）

### ISSUE THREAD

**Issue by javenhmh** [Mange/rtl8192eu-linux-driver#328] opened 2023-10-22 14:11 UTC
Compilation Failure on chromeOS Flex Linux（debian 11 bullseye）
============
hmh@penguin:/mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master$ sudo make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.10.0-26-amd64/build M=/mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master  modules
make[1]: 进入目录“/usr/src/linux-headers-5.10.0-26-amd64”
  CC [M]  /mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master/core/rtw_cmd.o
In file included from /usr/src/linux-headers-5.10.0-26-common/include/linux/jiffies.h:14,
                 from /usr/src/linux-headers-5.10.0-26-common/include/linux/ktime.h:25,
                 from /usr/src/linux-headers-5.10.0-26-common/include/linux/timer.h:6,
                 from /usr/src/linux-headers-5.10.0-26-common/include/linux/workqueue.h:9,
                 from /usr/src/linux-headers-5.10.0-26-common/include/linux/rhashtable-types.h:15,
                 from /usr/src/linux-headers-5.10.0-26-common/include/linux/ipc.h:7,
                 from /usr/src/linux-headers-5.10.0-26-common/include/uapi/linux/sem.h:5,
                 from /usr/src/linux-headers-5.10.0-26-common/include/linux/sem.h:5,
                 from /usr/src/linux-headers-5.10.0-26-common/include/linux/sched.h:15,
                 from /usr/src/linux-headers-5.10.0-26-common/include/linux/sched/signal.h:7,
                 from /mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master/include/osdep_service.h:25,
                 from /mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master/include/drv_types.h:32,
                 from /mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master/core/rtw_cmd.c:22:
./include/generated/timeconst.h:11:2: error: #error "include/generated/timeconst.h has the wrong HZ value!"
   11 | #error "include/generated/timeconst.h has the wrong HZ value!"
      |  ^~~~~
In file included from /usr/src/linux-headers-5.10.0-26-common/include/linux/slab.h:15,
                 from /mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master/include/osdep_service_linux.h:29,
                 from /mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master/include/osdep_service.h:45,
                 from /mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master/include/drv_types.h:32,
                 from /mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master/core/rtw_cmd.c:22:
/usr/src/linux-headers-5.10.0-26-common/include/linux/gfp.h: In function ‘gfp_zone’:
/usr/src/linux-headers-5.10.0-26-common/include/linux/gfp.h:430:20: warning: left shift count >= width of type [-Wshift-count-overflow]
  430 |  | (OPT_ZONE_DMA32 << (___GFP_MOVABLE | ___GFP_DMA32) * GFP_ZONES_SHIFT)\
      |                    ^~
/usr/src/linux-headers-5.10.0-26-common/include/linux/gfp.h:455:7: note: in expansion of macro ‘GFP_ZONE_TABLE’
  455 |  z = (GFP_ZONE_TABLE >> (bit * GFP_ZONES_SHIFT)) &
      |       ^~~~~~~~~~~~~~
In file included from /mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master/include/osdep_service.h:45,
                 from /mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master/include/drv_types.h:32,
                 from /mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master/core/rtw_cmd.c:22:
/mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master/include/osdep_service_linux.h: In function ‘_init_timer’:
/mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master/include/osdep_service_linux.h:253:8: error: ‘_timer’ {aka ‘struct timer_list’} has no member named ‘data’
  253 |  ptimer->data = (unsigned long)cntx;
      |        ^~
/mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master/include/osdep_service_linux.h:254:2: error: implicit declaration of function ‘init_timer’; did you mean ‘_init_timer’? [-Werror=implicit-function-declaration]
  254 |  init_timer(ptimer);
      |  ^~~~~~~~~~
      |  _init_timer
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-5.10.0-26-common/scripts/Makefile.build:291：/mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master/core/rtw_cmd.o] 错误 1
make[2]: *** [/usr/src/linux-headers-5.10.0-26-common/Makefile:1856：/mnt/chromeos/MyFiles/APK/rtl8192eu-linux-driver-master] 错误 2
make[1]: *** [/usr/src/linux-headers-5.10.0-26-common/Makefile:192：__sub-make] 错误 2
make[1]: 离开目录“/usr/src/linux-headers-5.10.0-26-amd64”
make: *** [Makefile:1335：modules] 错误 2

**Comment by CGarces** [comment] 2024-01-20 12:32
Looks like you are using the master branch?, please use the **realtek-4.4.x** branch

Duplicate of #76

**Closed as completed by CGarces** 2024-01-20 12:32 UTC
