### ISSUE TITLE
Packet Injection not working

### ISSUE THREAD

**Issue by chiragvshroff** [Mange/rtl8192eu-linux-driver#219] opened 2021-01-25 19:06 UTC
Monitor mode is working fine but packet injection isn't working at all I'm in Kali Linux 2020.4 please help me to fix the issue.

**Comment by systemedev** [comment] 2021-12-04 22:39
same issue here

**Comment by CGarces** [comment] 2021-12-06 09:57
Duplicate of #191
I don't have knowledge to this that.

**Closed as completed by CGarces** 2021-12-06 09:57 UTC
