### ISSUE TITLE
TL-WN8200ND (V2) slow connection

### ISSUE THREAD

**Issue by abalta** [Mange/rtl8192eu-linux-driver#160] opened 2020-01-26 00:44 UTC
This driver works for TL-WN8200ND model wi-fi adapter but, connections are slow and it has some authentication issue and sometimes see wi-fi networks sometimes don't.

**Comment by CGarces** [comment] 2020-02-01 11:23
Duplicate of #154

**Closed as completed by CGarces** 2020-02-01 11:23 UTC
