### ISSUE TITLE
unrecognized command line option ‘-mgeneral-regs-only’

### ISSUE THREAD

**Issue by belotn** [Mange/rtl8192eu-linux-driver#238] opened 2021-08-29 10:57 UTC
Hello,

I'm unable to build the module with osmc, dkms failed with "unrecognized command line option ‘-mgeneral-regs-only’" 

CONFIG_PLATFORM_ARM_RPI = y

Kernel version : 5.10.32-2-osmc

**Comment by CGarces** [comment] 2021-08-30 08:52
Duplicate of #203
CONFIG_PLATFORM_ARM_RPI = y is for ARM 32 bits
Try
make CONFIG_PLATFORM_ARM_AARCH64=y CONFIG_PLATFORM_I386_PC=n for 64 bits

**Closed as completed by CGarces** 2021-08-30 08:52 UTC

**Comment by belotn** [comment] 2021-08-30 09:38
Thanks, i've done 
`sudo apt-get install  rbp2-headers-$(uname -r)
sudo ln -s /usr/src/rbp2-headers-$(uname -r) /lib/modules/$(uname -r)/build
sudo make ARCH=arm
sudo make install
`
And all is good ! 
Thanks a lot !
