### ISSUE TITLE
Won't connect on Debian

### ISSUE THREAD

**Issue by karl6994** [Mange/rtl8192eu-linux-driver#51] opened 2017-09-01 07:42 UTC
Hello everyone, I tried getting my RTL8192eu USB adapter to work on Debian 32-bit a few weeks ago but it wouldn't connect to the networks... It finds them OK, but it won't actually connect to it, it just keeps prompting me for the password! This occurs on Debian Stretch stable and Debian Stretch testing (buster) repo. This driver works fine on Fedora... Strange. 
Any ideas on how to solve this?

**Comment by CGarces** [comment] 2017-09-01 11:58
Looks like a duplicate of #48 
Can you please check if the solution provided works for you?

The patch for ubuntu was released on  2017-08-24 ([network-manager 1.8.2-1ubuntu3](https://launchpad.net/ubuntu/+source/network-manager/1.8.2-1ubuntu3)), as I see at https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1681513

So maybe not is patched on Debian testing, [the package is from 2017-07-18](https://packages.qa.debian.org/n/network-manager.html) 

Don't hesitate to reopen the bug if the fix proposed at #48 not works for you.

**Closed by CGarces** 2017-09-01 11:58 UTC
