### ISSUE TITLE
Injection not working

### ISSUE THREAD

**Issue by harlequin2** [Mange/rtl8192eu-linux-driver#218] opened 2021-01-25 00:30 UTC
I have installed this driver in Kali 5.9 (USB TL-WN822N) and it installed OK, switches to monitor mode no prob, but no packet injection. aireplay-ng -9 wlan0 shows "No Answer" to broadcast probe requests and 0/30 0% for directed probe requests. It seems the unit is not transmitting. Also, no led activity. Airodump-ng displays received packets from half a dozen local APs.

**Comment by CGarces** [comment] 2021-01-25 12:03
Duplicate of #191

**Closed as completed by CGarces** 2021-01-25 12:03 UTC
