### ISSUE TITLE
Can't install dkms!

### ISSUE THREAD

**Issue by htb300** [Mange/rtl8192eu-linux-driver#224] opened 2021-02-08 15:56 UTC
sudo dkms install rtl8192eu/1.0
                                  
Error! echo
Your kernel headers for kernel 5.9.0-kali1-amd64 cannot be found at
/lib/modules/5.9.0-kali1-amd64/build or /lib/modules/5.9.0-kali1-amd64/source.
You can use the --kernelsourcedir option to tell DKMS where it's  #located.

I'm new to this. What should I do?

**Comment by CGarces** [comment] 2021-02-08 16:17
Duplicate of #212
Looks like you don't have the kernel sources.

**Closed as completed by CGarces** 2021-02-08 16:17 UTC
