### ISSUE TITLE
stuck on infinite loading loop after sudo dkms install rtl8192eu/1.0

### ISSUE THREAD

**Issue by 3sv1n** [Mange/rtl8192eu-linux-driver#286] opened 2022-08-21 12:46 UTC
While following the instructions for installing the driver I typed the command 
``sudo dkms install rtl8192eu/1.0``
The terminal just shows the ```...........``` loading screen and nothing happens. no error screen or freezing or anything. just shows the infinite full stops...
what's the problem??

**Comment by CGarces** [comment] 2022-08-22 11:39
Duplicate of #279
I can't reproduce the issue.

**Closed as completed by CGarces** 2022-08-22 11:39 UTC
