### ISSUE TITLE
Flooding

### ISSUE THREAD

**Issue by Nordicruler** [Mange/rtl8192eu-linux-driver#116] opened 2019-02-22 03:25 UTC
What is this flooding in dmesg? Im using gentoo.

`[    8.623534] RTL871X: duplicate tx power limit combination [band 2.4G][regulation MKK][bw 40M][rate section HT][rf path 2T][chnl 05]
[    8.623535] RTL871X: duplicate tx power limit combination [band 2.4G][regulation FCC][bw 40M][rate section HT][rf path 2T][chnl 06]
[    8.623536] RTL871X: duplicate tx power limit combination [band 2.4G][regulation ETSI][bw 40M][rate section HT][rf path 2T][chnl 06]
[    8.623537] RTL871X: duplicate tx power limit combination [band 2.4G][regulation MKK][bw 40M][rate section HT][rf path 2T][chnl 06]
[    8.623538] RTL871X: duplicate tx power limit combination [band 2.4G][regulation FCC][bw 40M][rate section HT][rf path 2T][chnl 07]
[    8.623539] RTL871X: duplicate tx power limit combination [band 2.4G][regulation ETSI][bw 40M][rate section HT][rf path 2T][chnl 07]
[    8.623542] RTL871X: duplicate tx power limit combination [band 2.4G][regulation MKK][bw 40M][rate section HT][rf path 2T][chnl 07]`

**Comment by CGarces** [comment] 2019-06-30 19:30
Duplicate of #79

**Closed as completed by CGarces** 2019-06-30 19:30 UTC
Labels: duplicate
