### ISSUE TITLE
continuous ask for authentication

### ISSUE THREAD

**Issue by pruebasTemporal** [Mange/rtl8192eu-linux-driver#162] opened 2020-02-04 04:24 UTC
He doesn't let me into monitor mode, he asks me for constant authentication
parrot
version 4.68 64 bits
kernel linux 5.4.0–2parrot1-amd64 x84_64.

**Comment by CGarces** [comment] 2020-10-24 13:14
Probably duplicate of #57
Please add more information if the information at #57 not solve your issue.

**Closed as completed by CGarces** 2020-10-24 13:14 UTC
Labels: duplicate
