### ISSUE TITLE
cannot enter monitor mode

### ISSUE THREAD

**Issue by nymda** [Mange/rtl8192eu-linux-driver#192] opened 2020-08-12 16:04 UTC
knedit@Kali:~$ sudo iwconfig wlan0 mode monitor
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan0 ; Invalid argument.

**Comment by CGarces** [comment] 2020-12-14 16:42
Duplicate of #83

**Closed as completed by CGarces** 2020-12-14 16:42 UTC
